#pragma once

#define PDPP_COMPILER_INTEL 3
#define PDPP_COMPILER_INTEL_STRING "Intel C++ Compiler"

#ifdef __INTEL_COMPILER

#define PDPP_COMPILER PDPP_COMPILER_INTEL
#define PDPP_COMPILER_STRING PDPP_COMPILER_INTEL_STRING

#define PDPP_CLANG_VERSION __INTEL_COMPILER

#ifdef __COUNTER__
#define PDPP_COUNTER_AVAILABLE 1
#define PDPP_COUNTER __COUNTER__
#else
#define PDPP_COUNTER_AVAILABLE 0
#endif

#endif